@startuml no-prompt-eng

skinparam shadowing false
skinparam BackgroundColor transparent

start
#LightSalmon:System prompt (First Instruction);
while (User has input?)
    #LightCyan:User input;
    #LightPink:LLM reply;  
    endwhile
    -[hidden]->
    detach

@enduml