---
version: "3.8"
services:
  backend:
    image: backend-gpu
    build: ./backend-gpu
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./backend-gpu/logs:/backend-gpu/logs

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
