---
version: "3"
services:
  database:
    image: mysql:8.3.0
    env_file:
      - .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    image: backend-gpu
    build: ./backend-gpu
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./backend-gpu/logs:/backend-gpu/logs

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
  reverse-proxy:
    image: nginx:latest
    command: >
      /bin/sh -c "
      envsubst '$${FRONTEND_CONTAINER_PORT} $${BACKEND_CONTAINER_PORT} $${NGINX_CONTAINER_PORT}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && 
      nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    env_file:
      - .env
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}"
    volumes:
      - ./reverse-proxy:/etc/nginx/conf.d/
