---
version: "3"
services:
  gpu:
    image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
