---
version: "3.8"
services:
  reverse-proxy:
    command: >
      /bin/sh -c "
      envsubst '$${FRONTEND_CONTAINER_PORT} $${BACKEND_CONTAINER_PORT} $${DOMAIN}' < /etc/nginx/conf.d/nginx.conf.ssl.template > /etc/nginx/conf.d/default.conf &&
      while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"