---
version: '3'
services:
  integration-tests:
    image: backend
    container_name: integration-tests
    command: >
      /bin/bash -c "
      pipenv install pytest &&
      pipenv run python -m pytest tests/integration"
    env_file:
      - .env
    depends_on:
      - backend
      - database
