---
version: '3'
services:
  integration-tests:
    image: backend
    container_name: integration-tests
    command: >
      /bin/bash -c "
      pipenv install pytest -q &&
      pipenv run python -m pytest tests/integration -vv"
    env_file:
      - .env
    volumes:
      - ./backend/logs:/backend/logs
    depends_on:
      - backend
      - database
