name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!backend/logs/**'
      - '!backend/model_evaluation/**'
      - '!backend/README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Remove dummy data
      run: |
        rm scripts/insert_dummy_data.sql

    - name: Run integration tests
      run: |
        docker compose -f compose.yaml -f compose.tests.yaml up integration-tests --build --force-recreate --renew-anon-volumes
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Shutdown services
      run: |
        docker compose -f compose.yaml -f compose.tests.yaml down -v
