name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!backend/logs/**'
      - '!backend/model_evaluation/**'
      - '!backend/README.md'
      - 'database/**'
      - '!database/README.md'
      - '!database/insert_dummy_data.sql'
      - 'scripts/run_backend_integration_tests.sh'
      - '.github/workflows/backend-ci.yml'

jobs:
  backend-integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        cp sample.env .env

    - name: Prevent dummy data from being inserted
      run: |
        rm database/insert_dummy_data.sql

    - name: Run integration tests
      run: |
        docker compose -f compose.yaml -f compose.tests.yaml up integration-tests --build --exit-code-from integration-tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Shutdown containers
      run: |
        docker compose -f compose.yaml -f compose.tests.yaml down

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: integration_tests log
        path: ./backend/logs/integration_tests.log