name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!backend/logs/**'
      - '!backend/model_evaluation/**'
      - '!backend/README.md'
      - 'database/**'
      - '!database/README.md'
      - '!database/insert_dummy_data.sql'
      - 'scripts/run_backend_integration_tests.sh'
      - '.github/workflows/backend-ci.yml'

jobs:
  backend-integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        cp sample.env .env

    - name: Grant execute permission to run_backend_integration_tests.sh
      run: |
        chmod +x scripts/run_backend_integration_tests.sh

    - name: Run integration tests
      run: |
        ./scripts/run_backend_integration_tests.sh
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
